# ============================================================================
# CONFIGURACIÓN PARA CREAR SVM CON SERVICIO FCP USANDO API REST DE ONTAP
# ============================================================================

# Configuración del clúster
cluster:
  host: cluster1.demo.netapp.com
  username: admin
  password: Netapp1!

# Configuración de la SVM FCP
svm: 
  name: svm_1_cluster

roles:
  - role: telcoedgeadmin
    svm: svm_1_cluster
    cmddirname: "volume file"
    access: all
  - role: telcoedgeadmin
    svm: svm_1_cluster
    cmddirname: "vserver"
    access: readonly
  - role: telcoedgeadmin
    svm: svm_1_cluster
    cmddirname: "security"
    access: readonly

